spring.application.name=GyanJyotiLMS

spring.security.user.name=user
spring.security.user.password=password

spring.datasource.url=jdbc:postgresql://db:5432/gyan-jyoti-lms
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=shinyraptor69

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

app.securityKey=this-is-a-security-key-that-needs-to-be-replaced-in-production
app.accessKeyExpiry=900000
